[build]
  command = "npm run build"
  environment = { 
    NODE_VERSION = "18", 
    NPM_FLAGS = "--legacy-peer-deps" 
  }
  publish = "/opt/build/repo/dist"

[context.production.environment]
  REVIEW_ID = ""
